name: "✨ Feature Request"
description: "Suggest a new feature or improvement for the kustomize-validator tool."
title: "[FEATURE] "
labels: ["feature request"]
assignees: []

body:
  - type: input
    id: feature
    attributes:
      label: "Feature Description"
      description: "Describe the feature you would like to see."
      placeholder: "e.g., Add support for keyword appearance in kustomization.yaml"

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits / Use Cases"
      description: "Explain why this feature would be useful."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternatives you've considered, if any."
